name: CI

on:
  workflow_dispatch: {}
  pull_request: {}

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
         mise_toml: |
            [tools]
            opa = "1.2.0"
            regal = "0.31.1"
      - name: OPA test
        run: opa test lib example
      - name: Run Regal
        run: regal lint --format github .
